insert into livro(
  id,
  numero_paginas ,
  autor ,
  titulo,
  genero,
  data_publicacao ,
  isbm ,
  resumo ,
  imagem_capa ,
  editora ,
  disponibilidade ,
  tags ,
  preco 
) values (
  '1234567891',
  10,
  'João',
  'Sobreantural',
  'terror',
  '2025-12-01',
  null,
  'Conta a história de dois irmãos, cobatendo o mundo sobrenatural',
  null,
  'são jorge',
  true,
  'terror,acao,drama',
  150.02
),
(
  '1234567892',
  320,
  'Maria Fernanda',
  'O Enigma do Vale',
  'mistério',
  '2024-05-12',
  null,
  'Um detetive aposentado retorna à sua cidade natal para investigar desaparecimentos estranhos.',
  null,
  'Luz & Vida',
  true,
  'mistério,suspense,investigacao',
  89.90
),
(
  '1234567893',
  210,
  'Carlos Henrique',
  'A Máquina do Tempo Perdido',
  'ficção científica',
  '2023-09-20',
  null,
  'Um cientista cria uma máquina capaz de manipular o tempo, mas enfrenta consequências inesperadas.',
  null,
  'TechBooks',
  true,
  'ficcao,sci-fi,aventura',
  120.00
),
(
  '1234567894',
  150,
  'Ana Luiza Ribeiro',
  'Cantos da Aurora',
  'poesia',
  '2022-02-10',
  null,
  'Coletânea de poemas que exploram sentimentos humanos, natureza e autoconhecimento.',
  null,
  'Verso Livre',
  true,
  'poesia,arte,reflexao',
  45.50
),
(
  '1234567895',
  480,
  'Rafael Moura',
  'Império de Sombras',
  'fantasia',
  '2021-11-30',
  null,
  'Um reino ameaçado pela ascensão de uma força sombria precisa de um herói improvável.',
  null,
  'Dragão Azul',
  true,
  'fantasia,aventura,magia',
  160.75
),
(
  '1234567896',
  190,
  'Juliana Alves',
  'Receitas da Vovó Lili',
  'culinária',
  '2019-08-03',
  null,
  'Livro com receitas tradicionais brasileiras passadas por gerações.',
  null,
  'Sabor & Arte',
  true,
  'culinaria,gastronomia,receitas',
  79.99
),
(
  '1234567897',
  260,
  'Pedro Antônio',
  'O Último Sobrevivente',
  'ação',
  '2020-01-15',
  null,
  'Um ex-militar precisa lutar para sobreviver após ser perseguido por uma organização secreta.',
  null,
  'Fênix',
  true,
  'acao,thriller,aventura',
  98.00
),
(
  '1234567898',
  340,
  'Lívia Martins',
  'Amores de Outono',
  'romance',
  '2023-04-09',
  null,
  'Uma história de amor marcada por reencontros, despedidas e superação.',
  null,
  'Corações Editora',
  true,
  'romance,drama,ficcao',
  65.40
),
(
  '1234567899',
  120,
  'Bruno Soares',
  'Guia Prático de Minimalismo',
  'autoajuda',
  '2022-07-21',
  null,
  'Um guia para simplificar a vida e priorizar o que realmente importa.',
  null,
  'Vida Leve',
  true,
  'autoajuda,organizacao,bem-estar',
  55.00
),
(
  '1234567810',
  500,
  'Helena Costa',
  'Civilizações Perdidas',
  'história',
  '2021-03-05',
  null,
  'Exploração detalhada de antigas civilizações e os mistérios que cercam seu desaparecimento.',
  null,
  'Raízes Editora',
  true,
  'historia,arqueologia,cultura',
  140.90
);